# Generated by Django 3.2.9 on 2021-11-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211130_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='commenter',
            new_name='comment_liker',
        ),
    ]
