# Generated by Django 3.2.9 on 2021-12-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_commenter_commentlike_comment_liker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
